config/routes.rb
Rails.application.routes.draw do
  root(to: 'home#index')

  resources(:users, only: [:new, :create, :show, :destroy, :edit, :update])
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many(:users)
end

app/models/user.rb
class User < ApplicationRecord
  validates(:email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i })
  validates(:password, presence: true, length: { minimum: 8, maximum: 20 }, confirmation: true,  on: :create)
  validates(:nickname, presence: true, length: { maximum: 10 })
  validates(:family_name, presence: true, length: { maximum: 10 })
  validates(:first_name, presence: true, length: { maximum: 10 })
  validates(:postal_code, presence: true, format: { with: /\d{7}/ })
  validates(:address, presence: true, length: { maximum: 50 })

  include(ActiveModel::Validations)
  validates_with(ImageExtensionValidator)

  has_secure_password
  has_one_attached(:image)

  belongs_to(:prefecture)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action(:set_user, only: [:show, :edit, :update, :destroy])
  before_action(:set_prefectures, only: [:new, :create, :edit, :update])

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    binding.pry
    if @user.save
      flash[:success] = '認証メールを送信しました。'
      redirect_to(root_url)
    else
      render('new')
    end
  end

  def edit
  end

  def update
    if @user.update(update_user_params)
      flash[:success] = 'ユーザー情報を更新しました。'
      redirect_to(@user)
    else
      render('edit')
    end
  end

  def destroy
    @user.destroy
    flash[:success] = 'ユーザーを削除しました。'
    redirect_to(root_url)
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :image,
        :nickname, :family_name, :first_name, :postal_code, :prefecture_id, :address)
    end

    def update_user_params
      params.require(:user).permit(:image, :nickname, :family_name, :first_name, :postal_code, :prefecture_id, :address)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def set_prefectures
      @prefectures = Prefecture.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_image(user, width)
    if user.image.attached?
      image_tag(user.image, class: "#{width}") #w-75
    else
      image_pack_tag('media/images/default.jpg', class: "#{width}")
    end
  end

  def prefecture_options(prefectures)
    prefectures.reduce([]) do |array, prefecture|
      array.push([prefecture.name, prefecture.id])
    end
  end
end

app/views/home/index.html.erb
<%= provide(:title, 'フリマ') %>

<div class="jumbotron jumbtron-fluid m-0">
  <div class="container">
    <h1>フリマ</h1>
    <p >フリマは配送料のみで出品された商品を買うことができるサイトです。</p>
    <%# ここに検索フォームを設置 %>
  </div>
</div>

<div class="container">
  <%# ここに新着商品を表示 %>
</div>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="py-4 bg-light">
  <div class="container text-center">
    <p class="m-0">Copyright &copy:2020 フリマ All Rights Reserved</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to('フリマ', '#', class: "navbar-brand") %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-text" aria-controls="navbar-text" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar-text">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to('新規登録', new_user_path, class: "nav-link") %>
        </li>
        <li class="nav-item">
          <%= link_to('ログイン', '#', class: "nav-link") %>
        </li>
        <li class="nav-item">
          <%= link_to('出品する', '#', class: "nav-link") %>
        </li>
        <li class="nav-item">
          <%= link_to('マイページ', '#', class: "nav-link") %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) || 'フリマ' %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'main.js' %>
    <%= stylesheet_pack_tag 'main.css' %>
  </head>

  <body>
    <%= render('layouts/header') %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %> m-0"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render('layouts/footer') %>
  </body>
</html>

app/views/users/edit.html.erb
<%= provide(:title, 'ユーザー情報編集') %>

<div class="container users-form">
  <h1>ユーザー情報編集</h1>

  <%= form_with(model: @user) do |f| %>

    <%= render('layouts/error_messages', object: @user) %>

    <div class="row form-group">
      <%= f.label(:image, class: "col-md-3") %>
      <%= f.file_field(:image, class: "col-md-9 form-control-file") %>
    </div>

    <div class="row form-group">
      <%= f.label(:nickname, class: "col-md-3") %>
      <%= f.text_field(:nickname, class: "col-md-9 form-control") %>
    </div>

    <div class="row form-group">
      <%= f.label(:family_name, class: "col-md-3") %>
      <%= f.text_field(:family_name, class: "col-md-9 form-control") %>
    </div>

    <div class="row form-group">
      <%= f.label(:first_name, class: "col-md-3") %>
      <%= f.text_field(:first_name, class: "col-md-9 form-control") %>
    </div>

    <div class="row form-group">
      <%= f.label(:postal_code, class: "col-md-3") %>
      <%= f.text_field(:postal_code, class: "col-md-9 form-control", 'v-model': 'user.postalCode') %>
    </div>

    <button class="btn btn-primary" @click.prevent="searchAddress">住所検索</button>

    <div class="row form-group">
      <%= f.label(:prefecture_id, class: "col-md-3") %>
      <%= f.collection_select(:prefecture_id, @prefectures, :id, :name, 'v-model': 'user.prefectureId') %>
    </div>

    <div class="row form-group">
      <%= f.label(:address, class: "col-md-3") %>
      <%= f.text_field(:address, class: "col-md-9 form-control", 'v-model': 'user.address') %>
    </div>

    <div class="d-flex justify-content-center">
      <%= f.submit('更新', class: "btn btn-primary text-center") %>
    </div>
  <% end %>
</div>

<%= javascript_pack_tag('views/users/new.js') %>

app/views/users/new.html.erb
<%= provide(:title, '新規登録') %>

<div class="container users-form">
  <h1>新規登録</h1>

  <%= form_with(model: @user) do |f| %>

    <%= render('layouts/error_messages', object: @user) %>

    <div class="row form-group">
      <%= f.label(:email, class: "col-md-3") %>
      <%= f.email_field(:email, class: "col-md-9 form-control") %>
    </div>

    <div class="row form-group">
      <%= f.label(:password, class: "col-md-3") %>
      <%= f.password_field(:password, class: "col-md-9 form-control") %>
    </div>

    <div class="row form-group">
      <%= f.label(:password_confirmation, class: "col-md-3") %>
      <%= f.password_field(:password_confirmation, class: "col-md-9 form-control") %>
    </div>

    <div class="row form-group">
      <%= f.label(:image, class: "col-md-3") %>
      <%= f.file_field(:image, class: "col-md-9 form-control-file") %>
    </div>

    <div class="row form-group">
      <%= f.label(:nickname, class: "col-md-3") %>
      <%= f.text_field(:nickname, class: "col-md-9 form-control") %>
    </div>

    <div class="row form-group">
      <%= f.label(:family_name, class: "col-md-3") %>
      <%= f.text_field(:family_name, class: "col-md-9 form-control") %>
    </div>

    <div class="row form-group">
      <%= f.label(:first_name, class: "col-md-3") %>
      <%= f.text_field(:first_name, class: "col-md-9 form-control") %>
    </div>

    <div class="row form-group">
      <%= f.label(:postal_code, class: "col-md-3") %>
      <%= f.text_field(:postal_code, class: "col-md-9 form-control", 'v-model': 'user.postalCode') %>
    </div>

    <button class="btn btn-primary" @click.prevent="searchAddress">住所検索</button>

    <div class="row form-group">
      <%= f.label(:prefecture_id, class: "col-md-3") %>
      <%= f.select(:prefecture_id, prefecture_options(@prefectures), class: 'form-control')%>
    </div>

    <div class="row form-group">
      <%= f.label(:address, class: "col-md-3") %>
      <%= f.text_field(:address, class: "col-md-9 form-control", 'v-model': 'user.address') %>
    </div>

    <div class="d-flex justify-content-center">
      <%= f.submit('登録', class: "btn btn-primary text-center") %>
    </div>
  <% end %>
</div>

<%= javascript_pack_tag('views/users/new.js') %>

app/views/users/show.html.erb
<%= provide(:title, 'マイページ') %>

<div class="container">
  <h1>マイページ</h1>
  <div class="row">
    <div class="col-md-3">
      <div class="text-center">
        <div><%= user_image(@user, 'w-75') %></div>
      </div>
      <%# ユーザーの評価を追加 %>
    </div>

    <div class="col-md-9">
      <table class="table table-striped table-bordered">
        <tbody>
          <tr>
            <th><%= User.human_attribute_name(:nickname) %></th>
            <td><%= @user.nickname %></td>
          </tr>
          <tr>
            <th><%= User.human_attribute_name(:family_name) %></th>
            <td><%= @user.family_name %></td>
          </tr>
          <tr>
            <th><%= User.human_attribute_name(:first_name) %></th>
            <td><%= @user.first_name %></td>
          </tr>
          <tr>
            <th><%= User.human_attribute_name(:postal_code) %></th>
            <td><%= @user.postal_code %></td>
          </tr>
          <tr>
            <th><%= User.human_attribute_name(:address) %></th>
            <td><%= @user.address %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <%= link_to('ユーザー情報編集', edit_user_path(@user), class: 'btn btn-primary mr-3') %>
  <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal1">退会する</button>
</div>

<div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="label1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body">
        <p>本当に退会しますか？</p>
        <div class="d-flex justify-content-end">
          <button type="button" class="btn btn-secondary mr-2" data-dismiss="modal">閉じる</button>
          <%= button_to('退会', @user, method: :delete , class: 'btn btn-danger') %>
        </div>
      </div>
    </div>
  </div>
</div>